OFFLINE_PRODUCTS = [
    {
        "id": 1,
        "title": "Essence Mascara Lash Princess",
        "price": 9.99,
        "category": "beauty",
    },
    {
        "id": 2,
        "title": "Eyeshadow Palette",
        "price": 19.99,
        "category": "beauty",
    },
    {
        "id": 3,
        "title": "Powder Canister",
        "price": 14.99,
        "category": "beauty",
    },
    {
        "id": 4,
        "title": "Red Lipstick",
        "price": 12.99,
        "category": "beauty",
    },
    {
        "id": 5,
        "title": "Red Nail Polish",
        "price": 8.99,
        "category": "beauty",
    },
    {
        "id": 6,
        "title": "Calvin Klein CK One",
        "price": 49.99,
        "category": "fragrances",
    },
    {
        "id": 7,
        "title": "Chanel Coco Noir Eau De",
        "price": 129.99,
        "category": "fragrances",
    },
    {
        "id": 8,
        "title": "Dior J'adore",
        "price": 89.99,
        "category": "fragrances",
    },
    {
        "id": 9,
        "title": "Dolce Shine Eau de",
        "price": 69.99,
        "category": "fragrances",
    },
    {
        "id": 10,
        "title": "Gucci Bloom Eau de",
        "price": 79.99,
        "category": "fragrances",
    },
    {
        "id": 11,
        "title": "Annibale Colombo Bed",
        "price": 1899.99,
        "category": "furniture",
    },
    {
        "id": 12,
        "title": "Annibale Colombo Sofa",
        "price": 2499.99,
        "category": "furniture",
    },
    {
        "id": 13,
        "title": "Bedside Table African Cherry",
        "price": 299.99,
        "category": "furniture",
    },
    {
        "id": 14,
        "title": "Knoll Saarinen Executive Conference Chair",
        "price": 499.99,
        "category": "furniture",
    },
    {
        "id": 15,
        "title": "Wooden Bathroom Sink With Mirror",
        "price": 799.99,
        "category": "furniture",
    },
    {
        "id": 16,
        "title": "Apple iPhone",
        "price": 799.99,
        "category": "smartphones",
    },
    {
        "id": 17,
        "title": "Samsung Galaxy",
        "price": 699.99,
        "category": "smartphones",
    },
    {
        "id": 18,
        "title": "Huawei Mate",
        "price": 599.99,
        "category": "smartphones",
    },
    {
        "id": 19,
        "title": "Oppo A9",
        "price": 399.99,
        "category": "smartphones",
    },
    {
        "id": 20,
        "title": "Realme X",
        "price": 299.99,
        "category": "smartphones",
    },
]